### ISSUE TITLE
pgi compiler on summit is not able to compile CXX function template correctly

### ISSUE THREAD

**Issue by phyboyzhang** [SCOREC/wdmapp_coupling#103] opened 2021-01-07 01:46 UTC
The coupler has a function template "distriDataAmongCollective"  in the header file "sendrecv_impl.h" and that template is invoked by "gemXgcDataproc.cc" file. The code can be compiled with pgi compiler. But the execution shows that the function "distriDataAmongCollective" is not compiled correctly.  If I change template name  "distriDataAmongCollective"  to "istriDataAmongCollective" but still keep  the name "distriDataAmongCollective" as invoked in "gemXgcDataproc.cc" file, and totally recompile the code from "cmake ..", the compile doesn't report the error of "distriDataAmongCollective" as undefined.

**Comment by cwsmith** [comment] 2021-01-07 12:27
@phyboyzhang 

There are critical details missing for me to attempt to reproduce this behavior.  Please provide the following info:

- branch, repo, and hash of the coupler version used
- the `cmake` command used to build the coupler
- the modules loaded on summit when running `cmake` and `make`

**Comment by phyboyzhang** [comment] 2021-01-07 15:23
The document for building and running the codes is given here:  https://github.com/SCOREC/wdmapp_coupling/wiki/Building-GEM-COUPLER-XGC-User-with-PGI-compiler-on-summit

**Comment by cwsmith** [comment] 2021-01-07 17:07
Thank you.

@phyboyzhang What was the fix for the template issue?

**Comment by phyboyzhang** [comment] 2021-01-07 17:17
I moved that template function into the corresponding  class as a class routine.  Then the compiler is able to  recognize and compile it.

**Comment by cwsmith** [comment] 2021-01-07 17:59
Would you please push the change to the repo?

**Comment by phyboyzhang** [comment] 2021-01-07 20:07
Here is update:  https://github.com/phyboyzhang/wdmapp_coupling-1/tree/pgitemplate

**Comment by phyboyzhang** [comment] 2021-01-08 22:21
It looks that the PGI compiler on summit can not correctly compile the absolute function "abs" of CXX. With the following lines
```
    if(p1->mype == 17 && li == p1->li1){
      for( LO m = 0; m<versurf[p1->li1]; m++) printf("m=%d, lk1=%d, %f, %f, %f \n", m, lk1, exterarr[m],
abs(exterarr[m]-interarr[lk1]), exterarr[m]-interarr[lk1]);
    }
```
I got the error output:
```
1: 17: m=0, lk1=6, -3.141527, 0.000000, -4.537791
1: 17: m=1, lk1=6, -3.138609, 0.000000, -4.534872
1: 17: m=2, lk1=6, -3.135689, 0.000000, -4.531952
1: 17: m=3, lk1=6, -3.132770, 0.000000, -4.529034
1: 17: m=4, lk1=6, -3.129852, 0.000000, -4.526116
1: 17: m=5, lk1=6, -3.126932, 0.000000, -4.523195
1: 17: m=6, lk1=6, -3.124013, 0.000000, -4.520276
1: 17: m=7, lk1=6, -3.121094, 0.000000, -4.517358
1: 17: m=8, lk1=6, -3.118173, 0.000000, -4.514437
1: 17: m=9, lk1=6, -3.115254, 0.000000, -4.511518
1: 17: m=10, lk1=6, -3.112335, 0.000000, -4.508598
1: 17: m=11, lk1=6, -3.109415, 0.000000, -4.505679
1: 17: m=12, lk1=6, -3.106497, 0.000000, -4.502761
1: 17: m=13, lk1=6, -3.103577, 0.000000, -4.499841
1: 17: m=14, lk1=6, -3.100659, 0.000000, -4.496922
```
Obviously, ''abs'' function maps any input into zero.

**Comment by phyboyzhang** [comment] 2021-01-08 22:57
But by adding the prefix std::, std::abs  works then, while gcc compiler doesn’t need that prefix.

**Comment by jacobmerson** [comment] 2022-03-04 17:51
Closing due to coupler rewrite.

**Closed by jacobmerson** 2022-03-04 17:51 UTC
Labels: bug, compilation, pgi
