### ISSUE TITLE
Coupler -TAU Performance Analysis Plan

### ISSUE THREAD

**Issue by Damilare06** [SCOREC/wdmapp_coupling#95] opened 2020-09-08 21:17 UTC
Form the documentation here, we have spelled out our performance analysis overview [here](https://github.com/SCOREC/wdmapp_coupling/wiki/XGC-GENE-Coupling-Performance-Optimization-Approach). The following questions remain unanswered;

- At a high level, what does `AssemDensiSendtoPart3`  do?
This routine is to arrange the 2D density arrays on each process into a global array. It involves the assignment of the boundary buffer in the `z` direction, the 3D density interpolation, data conversion from complex to real and density data reshuffling after gathering

- At a high level, 4 phases have been identified within `AssemDensiSendtoPart3` 
  - `setup1`: creating the global 3D array
  - `setup2`: transferring some local and interpolated density values into the global array
  - `exchange`: performing the `mpi_gather` and `reshuffle` in the `z` direction
  - `cleanup`: freeing allocated memory

- How much time per timestep is spent in `AssemDensiSendtoPart3` relative to the total time? 
 For a 1 timestep run, the below images show the timing info on each process. Please note that time as a percent of the total time grows with increasing time step.

`process 0`: 8.6s/86s = 10%
![n0-stats-inclusive-1](https://user-images.githubusercontent.com/46372584/92507268-b4637880-f1d4-11ea-8aba-ed901128cd18.jpg)

`process 1`: 8.6s/86s = 10%
![n1-stats-inclusive-1](https://user-images.githubusercontent.com/46372584/92507281-b62d3c00-f1d4-11ea-84af-4b42e3d2679e.jpg)

`process 2`: 21s/86s = 24%
![n2-stats-inclusive-1](https://user-images.githubusercontent.com/46372584/92507286-b9282c80-f1d4-11ea-8ccf-28ff61ee68b1.jpg)

`process 3`: 21s/86s = 24%
![n3-stats-inclusive-1](https://user-images.githubusercontent.com/46372584/92507288-b9282c80-f1d4-11ea-90f5-028c77222ec4.jpg)

- Are the inputs to the phases labelled 'setup1' and 'setup2' below the same for each RK iteration and/or time step? 
Yes, the inputs into `setup 1 & 2` are fixed across time steps;

```
 8961 setup 1
 8962 rank: 3 ,p3->li0: 90, p3->lj0: 32 p3->mylk0[0]: 686, p3->mylk0[2]: 695
 8963 setup 1
 8964 rank: 2 ,p3->li0: 90, p3->lj0: 32 p3->mylk0[0]: 685, p3->mylk0[2]: 695
 8965 setup 1
 8966 rank: 0 ,p3->li0: 90, p3->lj0: 32 p3->mylk0[0]: 35, p3->mylk0[2]: 42
 8967 setup 1
 8968 rank: 1 ,p3->li0: 90, p3->lj0: 32 p3->mylk0[0]: 34, p3->mylk0[2]: 40
```

```
 8067 setup 2
 8068 rank: 1 ,p1->li0: 90, p1->lj0: 16 n_cuts: 32
 8069 rank: 1 ,p1->npz: 2, p3->blockcount: 62213 p3->versurf[0]: 69, p3->versurf[1]: 76
 8070 setup 2
 8071 rank: 0 ,p1->li0: 90, p1->lj0: 16 n_cuts: 32
 8072 rank: 0 ,p1->npz: 2, p3->blockcount: 62213 p3->versurf[0]: 69, p3->versurf[1]: 76
 8073 setup 2
 8074 rank: 2 ,p1->li0: 90, p1->lj0: 16 n_cuts: 32
 8075 rank: 2 ,p1->npz: 2, p3->blockcount: 160326 p3->versurf[0]: 69, p3->versurf[1]: 76
 8076 setup 2
 8077 rank: 3 ,p1->li0: 90, p1->lj0: 16 n_cuts: 32
 8078 rank: 3 ,p1->npz: 2, p3->blockcount: 160326 p3->versurf[0]: 69, p3->versurf[1]: 76
```

- What is the timing for the 4 phases? 
```
 5731 rank 1 setup1 took 0.009642 seconds
 5732 rank 0 setup1 took 0.009823 seconds
 5733 rank 2 setup1 took 0.025053 seconds
 5734 rank 3 setup1 took 0.025047 seconds

 5735 rank 1 setup2 took 1.436609 seconds
 5736 rank 0 setup2 took 1.469711 seconds
 5741 rank 2 setup2 took 3.735463 seconds
 5742 rank 3 setup2 took 3.735804 seconds


 5737 rank 0 exchange took 0.113759 seconds
 5738 rank 1 exchange took 0.140350 seconds
 5743 rank 2 exchange took 0.237557 seconds
 5744 rank 3 exchange took 0.236666 seconds

 5739 rank 0 cleanup took 0.000424 seconds
 5740 rank 1 cleanup took 0.000430 seconds
 5745 rank 2 cleanup took 0.000416 seconds
 5746 rank 3 cleanup took 0.000384 seconds
```

From the above, `setup2` appears to be the most expensive parts of the exclusive timing.

**Comment by cwsmith** [comment] 2020-09-09 18:53
@Damilare06 How were the times collected for the four phases?  Is the code on github?  Adding up the times for the four phases for any given process gives a much smaller time than the TAU timing and I'm not sure why.

**Comment by Damilare06** [comment] 2020-09-09 19:02
Yes, I noticed the same, the code is here https://github.com/Damilare06/wdmapp_coupling/tree/perfstub

specifically - https://github.com/Damilare06/wdmapp_coupling/blob/1f72174d5854407ecdf8f0a80ba99c3d12bd8e0b/src/dataprocess.cc#L482

**Comment by cwsmith** [comment] 2020-09-09 19:20
I don't see any issues in the https://github.com/Damilare06/wdmapp_coupling/blob/1f72174d5854407ecdf8f0a80ba99c3d12bd8e0b/src/dataprocess.cc#L482 .

I assume the same case and time steps were used for run with TAU timing and the run using `MPI_Wtime()`?

With a timer for the entire `AssemDensiSendtoPart3` function, and the full run of the coupler, we could check if the percentages (`AssemDensiSendtoPart3`/total) were similar to the TAU timings.

**Comment by Damilare06** [comment] 2020-09-09 19:38
Yes, the same case and timesteps are used.
To be sure, I can replace this tau results table with new ones extracted from this new run with MPI_Wtime.  I have compared them and they are very similar.

okay, I would run once again with an MPI_Wtime for the entire function and see what result it returns.

**Comment by Damilare06** [comment] 2020-09-09 20:01
The timing agrees with the perfstubs output when we compare against the Exclusive time (not including the calls made to other functions)
```
5740 rank 0 AssemDens took 2.177385 seconds
5742 rank 1 AssemDens took 2.177438 seconds
5748 rank 3 AssemDens took 5.518552 seconds
5750 rank 2 AssemDens took 5.518611 seconds
```

**Comment by cwsmith** [comment] 2020-09-09 20:09
A timer around the entire contents of `AssemDensiSendtoPart3` would be 'inclusive'.  I don't understand what comparison is being made against the TAU `Exclusive` time.

**Comment by Damilare06** [comment] 2020-09-09 20:18
> A timer around the entire contents of `AssemDensiSendtoPart3` would be 'inclusive'. I don't understand what comparison is being made against the TAU 'exclusive' time.

Yes, my point was that even the `MPI_Wtime` value is way smaller than the exclusive result (disregarding the calls). 

Whereas it should be compared against inclusive.

**Comment by Damilare06** [comment] 2020-09-09 20:21
Are there any logical reasons for this? and might an MPI_barrier make the results more similar

**Comment by cwsmith** [comment] 2020-09-09 20:25
After checking the TAU documentation, we should ask the TAU folks how much overhead is in the TAU timings.

**Comment by khuck** [comment] 2020-09-09 23:15
OK, just cloned the repo and looking at the instrumentation... I also need to catch up on this conversation

**Comment by khuck** [comment] 2020-09-09 23:47
@Damilare06 @cwsmith If you're concerned about measurement overhead (which this could very well be) - one observation... remove the instrumentation around `minloc`, `minimalvalue`, and *definitely* `Lag3dInterpolD`.  And probably `ExecuteRealToComplex`.  Those functions are way too small and get called too often to get instrumented.  As a general rule, you shouldn't instrument _everything_ - just the important regions/phases.  You could be introducing way too much overhead by instrumenting those small functions.  For example: https://github.com/Damilare06/wdmapp_coupling/blob/da6adaf1f577d9592b9f8e60284780b2ae90c603/src/fourierdataproc.cc#L110-L119 is just an if statement and (maybe) a function call.  It will take longer to measure that function than to execute it.  There are probably others, those are just the ones that stand out in the profile data.

TAU automatically disables "throttling" when the PerfStubs implementation is used, because of the needed support for `PERFSTUBS_STOP_CURRENT()`.  Usually, TAU would notice that a function like `Lag3dInterpolD` has been called at least 100,000 times and the average time is less than 10us, and will disable that timer.

There's also a big load imbalance issue here - look at how many times `Lag3dInterpolD` is called on nodes 0 and 1 (~1.9e6), vs. how many times on nodes 2 and 3 (~5.1e6).  

Another suggestion -  since this is all C++ code, I recommend using `PERFSTUBS_SCOPED_TIMER_FUNC()`, because it will be faster than the `PERFSTUBS_START_STRING/PERFSTUBS_STOP_STRING` versions (no string construction, no hash table lookup, etc.) and because it will stop the timer automatically when it goes out of scope.  But that's not a critical change.  You can use `PERFSTUBS_SCOPED_TIMER(__func__)` instead if you don't want the file/line info in the timer name.  To use it, just put `PERFSTUBS_SCOPED_TIMER(__func__)` at the top of the function, no need to explicitly stop the timer.

**Comment by Damilare06** [comment] 2020-09-10 03:52
Swapping the `PERFSTUBS_START_STRING/PERFSTUBS_STOP_STRING ` for `PERFSTUBS_SCOPED_TIMER(__func__)` and removing implementations for those functions reduced runtime by about 8% to 79.381 seconds.

However, it does not address the timing mismatch between the `tau` implementation and the MPI_Wtime results for the `AssemDensiSendtoPart3` function; exclusively, `tau` reports 5.988 secs while `mpi` reports 1.594 secs


The code for the `MPI_Wtime` check can be found [here](https://github.com/Damilare06/wdmapp_coupling/blob/ad8ebba8c075c3e8f51e8950581e284b855f9a28/src/dataprocess.cc#L471)

Might there be a valid reason for this and if so, how can we minimize or synchronize both timers?

The tar ball contains the updated images of the timing per process
[1-updated.tar.gz](https://github.com/SCOREC/wdmapp_coupling/files/5199089/1-updated.tar.gz)

**Comment by khuck** [comment] 2020-09-10 15:15
Ah, that all makes sense.  I was going to suggest the callpath setting, glad it was helpful.

MPI_Wtime is just a timestamp, it isn't necessarily inclusive or exclusive.  Without a lot of extra logic and subtracting of child call times it is usually inclusive.

**Comment by Damilare06** [comment] 2020-09-10 16:59
Thank you very much Kevin.

Running the un-instrumented coupler for 1 timestep but with the `MPI_Wtime` shows 

```
10197 rank 2 Total simulation took 261.276749 seconds                                                 
10199 rank 3 Total simulation took 261.277150 seconds                          
10201 rank 0 Total simulation took 261.277495 seconds
10203 rank 1 Total simulation took 261.277374 seconds
```
This pales in comparison to the `tau` instrumented code that takes about 81 seconds per process.
Is there a logical explanation for this?

**Comment by khuck** [comment] 2020-09-10 17:14
TAU made it faster!  :)

Seriously, though - are you sure you compared them fairly?  That looks like a compiler flag difference, like -O0 instead of -O3.  Did you miss or change a flag?

**Comment by Damilare06** [comment] 2020-09-10 17:56
> TAU made it faster! :)
> 
> Seriously, though - are you sure you compared them fairly? That looks like a compiler flag difference, like -O0 instead of -O3. Did you miss or change a flag?

I would confirm that now

**Comment by Damilare06** [comment] 2020-09-11 15:53
I took your advice and built the coupler (with tau instrumentation) and the coupler without instrumentation (`develop`) with the same setup and the timing for the one without `tau` stays the same

```
10197 rank 1 Total simulation took 265.328732 seconds 
10199 rank 3 Total simulation took 265.329485 seconds            
10201 rank 2 Total simulation took 265.329581 seconds                                    
10203 rank 0 Total simulation took 265.329719 seconds
```

Might there be a logical reason for the coupler being slow when run without `tau`?

@phyboyzhang  & @cwsmith please can you confirm the run time for 1 timestep?

**Comment by khuck** [comment] 2020-09-11 16:22
That's really odd.  I can understand a slight difference, but this is ~3x difference.  The builds should be the same, but you can disable the PerfStubs instrumentation by not defining `PERFSTUBS_USE_TIMERS` at compile time.  Otherwise, the builds should be the same.

**Comment by Damilare06** [comment] 2020-09-11 18:15
I included the MPI_Wtiming into the `tau` instrumented coupler to estimate the runtime for a single timestep and I get an answer similar to the `tau` timing.  Also, I now get similar timing for the non-tau coupler. 

However `tau` instrumentation appears a few seconds faster (my non-tau run script was running a different xgc version)

`tau instrumented coupler`
```
11057 rank 3 Total simulation took 82.426731 seconds
11097 rank 2 Total simulation took 82.435036 seconds
11100 rank 0 Total simulation took 82.435403 seconds
11103 rank 1 Total simulation took 82.435583 seconds
```

`coupler@develop (no-tau)`

```
10194 rank 2 Total simulation took 84.269595 seconds
10196 rank 3 Total simulation took 84.269894 seconds
10198 rank 1 Total simulation took 84.270117 seconds
10203 rank 0 Total simulation took 84.328112 seconds
```

**Comment by khuck** [comment] 2020-09-11 18:44
Is it consistently faster?  Sometimes those differences are due to MPI Initialization times, or network variability, etc.

**Comment by Damilare06** [comment] 2020-09-13 15:41
No it is not consistently faster.

```
10200 rank 1 Total simulation took 80.416082 seconds
10202 rank 0 Total simulation took 80.416400 seconds
10204 rank 2 Total simulation took 80.416638 seconds
10206 rank 3 Total simulation took 80.416757 seconds
```
```
10200 rank 1 Total simulation took 79.609102 seconds                                                  
10202 rank 2 Total simulation took 79.609181 seconds                           
10204 rank 3 Total simulation took 79.609669 seconds
10206 rank 0 Total simulation took 79.609781 seconds
```

```
0194 rank 3 Total simulation took 82.813609 seconds                          
10196 rank 1 Total simulation took 82.813941 seconds
10198 rank 2 Total simulation took 82.814036 seconds
10203 rank 0 Total simulation took 82.859544 seconds
```

**Comment by cwsmith** [comment] 2020-09-25 15:30
@Damilare06 For ranks 0 and 1, and ranks 2 and 3, what are the values of the following variables?

`p1->li0`
`p1->lj0`
the min/max/avg of `p3->mylk0[0:p1->li0]`
`p1->n_cuts`
`p3->lj0`

which define the loop ranges here:

https://github.com/SCOREC/wdmapp_coupling/blob/1fa8726657fa356561e015ece53d7a23501eeab4/src/dataprocess.cc#L493-L513

**Comment by Damilare06** [comment] 2020-09-26 13:47
> @Damilare06 For ranks 2 or 3 ([these are the ranks with the longer runtime](https://github.com/SCOREC/wdmapp_coupling/wiki/XGC-GENE-Coupling-Performance-Optimization-Approach#optimizing-the-most-expensive-routine---assemdensisendtopart3)) what are the values of the following variables? Note, I'm assuming ranks 2 and 3 have nearly the same values.
> 
> `p1->li0`
> `p1->lj0`
> the min/max/avg of `p3->mylk0[0:p1->li0]`
> `p1->n_cuts`
> `p3->lj0`
> 
> which define the loop ranges here:
> 
> https://github.com/SCOREC/wdmapp_coupling/blob/1fa8726657fa356561e015ece53d7a23501eeab4/src/dataprocess.cc#L493-L513

```
 756 rank: 0 ,p1->li0: 90, p1->lj0: 16 n_cuts: 32 ,p1->npz: 2, p3->blockcount: 62213 p3->versurf[0]: 69, p3->versurf[1]: 76
 758 rank: 1 ,p1->li0: 90, p1->lj0: 16 n_cuts: 32 ,p1->npz: 2, p3->blockcount: 62213 p3->versurf[0]: 69, p3->versurf[1]: 76
 760 rank: 2 ,p1->li0: 90, p1->lj0: 16 n_cuts: 32 ,p1->npz: 2, p3->blockcount: 160326 p3->versurf[0]: 69, p3->versurf[1]: 76
 762 rank: 3 ,p1->li0: 90, p1->lj0: 16 n_cuts: 32,p1->npz: 2, p3->blockcount: 160326 p3->versurf[0]: 69, p3->versurf[1]: 76
```

**Comment by cwsmith** [comment] 2020-09-26 15:11
Thank you.

Are `p3->lj0` and `p3->mylk0[0:p1->li0]` based on `p1->npz`, `p3->blockcount`, `p3->versurf[0]`, and/or `p3->versurf[1]` ?

**Comment by Damilare06** [comment] 2020-09-26 18:42
No, Those were results from earlier tests (I have to wait for a while to get summit nodes)
`avg_it: average of p3->mylk0[0:p1->li0]`
```
 756 rank: 1 ,avg_it: 345.688889
 757 rank: 0 ,avg_it: 345.566667
 758 rank: 2 ,avg_it: 890.377778
 759 rank: 3 ,avg_it: 891.022222
```

**Comment by cwsmith** [comment] 2020-09-27 03:31
Thank you.  

And if I'm reading the `Part3Mesh3D::init(...)` function correctly,
https://github.com/SCOREC/wdmapp_coupling/blob/1fa8726657fa356561e015ece53d7a23501eeab4/src/importpart3mesh.cc#L103
`p3->lj0`would be 32 (`p1->lj0*2`) in this case.  Do we have output to confirm that?

**Comment by cwsmith** [comment] 2020-09-27 05:49
The repo here (almost) contains the minimal code needed to run the loops being discussed:

https://github.com/cwsmith/dotprod/

@Damilare06 A few more questions:

- From the table here:
https://github.com/SCOREC/wdmapp_coupling/wiki/XGC-GENE-Coupling-Performance-Optimization-Approach#optimizing-the-most-expensive-routine---assemdensisendtopart3
ranks 2 and 3 spend 3.7 seconds in `setup2` for four calls (one for each RK step) to `AssemDensiSendtoPart3`.  So, one execution of `setup2` is about 0.925 seconds.   Is that correct?
- Would you please point me at the code with the `dataprocess.cc` 'setup[1-4]' timers?  
- What is the size of the second dimension of the `tmp` array here?  https://github.com/SCOREC/wdmapp_coupling/blob/1fa8726657fa356561e015ece53d7a23501eeab4/src/dataprocess.cc#L527-L530

**Comment by Damilare06** [comment] 2020-09-27 16:47
> Thank you.
> 
> And if I'm reading the `Part3Mesh3D::init(...)` function correctly,
> https://github.com/SCOREC/wdmapp_coupling/blob/1fa8726657fa356561e015ece53d7a23501eeab4/src/importpart3mesh.cc#L103
> 
> 
> `p3->lj0`would be 32 (`p1->lj0*2`) in this case. Do we have output to confirm that?

Yes, it is correct.
```
 756 rank: 1 ,avg_it: 345.688889, p3->lj0: 32 
 757 rank: 0 ,avg_it: 345.566667, p3->lj0: 32 
 758 rank: 2 ,avg_it: 890.377778, p3->lj0: 32 
 759 rank: 3 ,avg_it: 891.022222, p3->lj0: 32
```

**Comment by Damilare06** [comment] 2020-09-27 19:28
Yes, ranks 2 and 3 spend 0.925 seconds within `setup2`. 

`setup2` code is here https://github.com/SCOREC/wdmapp_coupling/blob/1fa8726657fa356561e015ece53d7a23501eeab4/src/dataprocess.cc#L486-L530

The second dimension of the `tmp` array varies across processes (0&1 have similar values while 2&3 have similar values) and indexes
```
 828 rank: 0, p3->versurf[p3->li1+i]: 1332
 829 rank: 0, p3->versurf[p3->li1+i]: 1342
 830 rank: 0, p3->versurf[p3->li1+i]: 1351
 831 rank: 0, p3->versurf[p3->li1+i]: 1361

1097 rank: 3, p3->versurf[p3->li1+i]: 1959
1098 rank: 3, p3->versurf[p3->li1+i]: 1964
1099 rank: 3, p3->versurf[p3->li1+i]: 1969
1100 rank: 3, p3->versurf[p3->li1+i]: 1973
1101 rank: 3, p3->versurf[p3->li1+i]: 1978
1102 rank: 3, p3->versurf[p3->li1+i]: 1983
```

**Comment by Damilare06** [comment] 2020-09-28 15:26
The `coupler@develop` code with `MPI_Wtime` is [here](https://github.com/Damilare06/wdmapp_coupling/tree/wtime)

**Comment by cwsmith** [comment] 2020-09-28 19:54
Thank you.  For one call to the `setup2` code https://github.com/cwsmith/dotprod recorded .356 seconds which is 90% of the 'real' timing posted above (1.58/4 = .395).  I think this is close enough to proceed with work on tuning the simple code instead of worrying about running multi-node summit jobs.

In the tables/figures showing call counts on each process here:
https://github.com/SCOREC/wdmapp_coupling/issues/95#issue-696184005
ranks 0 and 1 spend about 10 seconds in `MPI_Gather` (rank 2 and 3 are near zero).  I don't see our code calling `MPI_Gather`:

```
~/develop/wdmapp_coupling (develop)$ grep -ri mpi_gather .
~/develop/wdmapp_coupling (develop)$ git log --oneline -1
1fa8726 (HEAD -> develop, origin/develop) Merge pull request #91 from Damilare06/develop
```

Note, our code has several calls to `MPI_Allgather[v]`:

```
~/develop/wdmapp_coupling (develop)$ grep -ri mpi_allgather .
./src/dataprocess.cc:  MPI_Allgather(&p1->lk0,1,mpitype,recvcount,1,mpitype,p1->comm_z); 
./src/dataprocess.cc:      MPI_Allgatherv(potentpart1[i][j],p1->lk0,MPI_CXX_DOUBLE_COMPLEX,tmp,recvcount,rdispls,
./src/dataprocess.cc:      MPI_Allgather(&p3->mylk0[i],1,mpitype,recvcount,1,mpitype,p1->comm_z); 
./src/dataprocess.cc:      MPI_Allgatherv(tmp_one,p3->mylk0[i],MPI_DOUBLE,tmp,recvcount,rdispls,
./src/dataprocess.cc:      MPI_Allgather(&p3->mylk0[i],1,mpitype,recvcount,1,mpitype,p1->comm_z); 
./src/dataprocess.cc:      MPI_Allgatherv(tmpmat[i][j],p3->mylk0[i],MPI_DOUBLE,tmp[i],recvcount,rdispls,
./src/importpart3mesh.cc:     MPI_Allgather(xinds,3,MPI_INT,buffer,3,MPI_INT,p1pp3d.comm_x);
./src/importpart3mesh.cc:	 MPI_Allgather(&mylk0[i],1,MPI_INT,recvcount,1,MPI_INT,p1pp3d.comm_z);
./src/importpart3mesh.cc:  MPI_Allgather(MPI_IN_PLACE,1,mpitype,inds,1,mpitype,comm_x);
```

Can Tau give us a call trace/stack/path for the `MPI_Gather` calls?

**Comment by Damilare06** [comment] 2020-09-28 20:31
If you are running develop, then there currently exists no tau` implementation in-there. So the `mpi_gather` shouldn't be from `tau`

**Comment by khuck** [comment] 2020-09-28 20:44
> Can Tau give us a call trace/stack/path for the `MPI_Gather` calls?

Yes, but it might be unstable on Summit.  If you set `export TAU_CALLSITE=1` in the environment before running, TAU will use libunwind to walk up the call stack at each timer to get its parent function.  Unfortunately, libunwind is unstable on ppc64le (known bug).  But it's worth a try...

**Comment by cwsmith** [comment] 2020-09-29 00:08
@Damilare06  Thanks for checking the call count for `MPI_Allgather[v]`.  At this point they are not a concern as they are not near the top in the list of expensive calls from the opening post or in this list/figure here: https://github.com/SCOREC/wdmapp_coupling/wiki/XGC-GENE-Coupling-Performance-Optimization-Approach#existing-performance-overview.

As I understand, the figures in the opening post were generated with TAU; for example
https://user-images.githubusercontent.com/46372584/92507268-b4637880-f1d4-11ea-8aba-ed901128cd18.jpg.
I **suspect** they are coming from ADIOS2, but if a more aggressive/intrusive TAU profiling mode was used then it is possible that TAU is the source.

@khuck Thank you for the approach and warning.  We should be able to run on Rhea if it is still available.

**Comment by cwsmith** [comment] 2020-09-29 13:18
The ADIOS2 folks confirmed that ADIOS2 is calling `MPI_Gather[v]`: https://github.com/SCOREC/wdmapp_coupling/issues/93#issuecomment-700690705 .

**Comment by jacobmerson** [comment] 2022-03-04 17:51
Closing due to coupler rewrite.

**Closed by jacobmerson** 2022-03-04 17:51 UTC
